### PR TITLE
fixes for g2 boxes

### PR DESCRIPTION
**Pull request by ksimuk**

### CODE REVIEW

**Comment by ghost** [comment]
1. 2. Top command sorting .. Top command different to that in the guides 
   top

**Comment by ghost** [comment]
1. Shell sessions ..config dir not present

**Comment by ksimuk** [comment]
> Top command sorting .. Top command different to that in the guides

do not think it is a problem, in guides it just example

>     Shell sessions ..config dir not present

fixed

**Comment by ghost** [comment]
A: 3. Background processes. The steps to follow do not seem to work? 1, 2 are OK, for 3, no requirement to 'return' key but 4 (shift+r) doesn't appear to sort by ascending order

**Pull request merged**
